### ISSUE TITLE
[Technical Review] 워드클라우드 API 기술적 검토

### ISSUE THREAD

**Issue by hwangheejung** [Team-Apricot/apricot-application#8]
## 📄 설명
Word Cloud API를 프로젝트에 적용 가능한지 기술적 확인

## 🗓️ TO-DO
- [x] Word Cloud를 적용할 설계된 레이아웃에 출력 해보기
- [x] 미흡한 디자인 요소 수정하기

**Comment by IToriginal** [comment]
- #13 
- 기술적으로 적용 가능한 것이 확인 되었으며, WordCloud에 출력될 key : value 형식에 값은 회의를 통해서 아래와 같이 진행하기로 하였음.
1) AOP 활용: 사용자의 검색이 많은 지역구를 확인
2) 지역구별 혜택 개수
- 러닝커브가 높은 1안을 우선 시도해보고, 프로젝트의 기간에 따라 2안이 적용될 수 있음
